# Generated by Django 4.2.16 on 2026-04-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "db_table": "diseases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FamilyDiseaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.CharField(
                        choices=[("husband", "Husband"), ("wife", "Wife")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Disease Entry",
                "verbose_name_plural": "Family Disease Entries",
                "db_table": "family_disease_entries",
            },
        ),
        migrations.CreateModel(
            name="FamilyRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("husband_name", models.CharField(max_length=150)),
                ("wife_name", models.CharField(max_length=150)),
                ("address", models.TextField()),
                ("nic_number", models.CharField(max_length=20)),
                ("husband_dob", models.DateField()),
                ("wife_dob", models.DateField()),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("job", models.CharField(max_length=100)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("no_formal", "No Formal Education"),
                            ("primary", "Primary (Grade 1–5)"),
                            ("secondary", "Secondary (Grade 6–10)"),
                            ("ol", "O/L Passed"),
                            ("al", "A/L Passed"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor's Degree"),
                            ("postgrad", "Master's / Postgraduate"),
                        ],
                        default="no_formal",
                        max_length=20,
                    ),
                ),
                ("marriage_date", models.DateField()),
                ("women_special_info", models.TextField(blank=True, default="")),
                (
                    "women_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "women_height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "men_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "men_height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moh_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_registrations",
                        to="areas.moharea",
                    ),
                ),
                (
                    "phm_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_registrations",
                        to="areas.phmarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Registration",
                "verbose_name_plural": "Family Registrations",
                "db_table": "family_registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
