# Generated by Django 4.2.16 on 2026-04-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("family", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="familyregistration",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="familydiseaseentry",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="family_entries",
                to="family.disease",
            ),
        ),
        migrations.AddField(
            model_name="familydiseaseentry",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_entries",
                to="family.familyregistration",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familydiseaseentry",
            unique_together={("registration", "disease", "person")},
        ),
    ]
