# Generated by Django 4.2.16 on 2026-04-04 19:25

import apps.uploads.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("family", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to=apps.uploads.models.upload_path)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("report", "Medical Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to="family.familyregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Upload",
                "verbose_name_plural": "File Uploads",
                "db_table": "file_uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
