# Generated by Django 4.2.16 on 2026-04-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MOHArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MOH Area",
                "verbose_name_plural": "MOH Areas",
                "db_table": "moh_areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PHMArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "PHM Area",
                "verbose_name_plural": "PHM Areas",
                "db_table": "phm_areas",
                "ordering": ["name"],
            },
        ),
    ]
