# Generated by Django 4.2.16 on 2026-04-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="phmarea",
            name="assigned_midwife",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "midwife"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_area",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="phmarea",
            name="moh_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phm_areas",
                to="areas.moharea",
            ),
        ),
    ]
