# Generated by Django 4.2.16 on 2026-04-22 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("areas", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MidwifeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Home Visit", "Home Visit")], max_length=50
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "midwife",
                    models.ForeignKey(
                        limit_choices_to={"role": "midwife"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midwife_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "midwife_schedules",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
