# Generated by Django 4.2.16 on 2026-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_midwifeschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midwifeschedule',
            name='type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Home Visit', 'Home Visit')], max_length=50),
        ),
    ]
