# Generated by Django 4.2.16 on 2026-05-02 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_response_rows(apps, schema_editor):
    MidwifeSchedule = apps.get_model("areas", "MidwifeSchedule")
    Resp = apps.get_model("areas", "MidwifeScheduleResponse")
    for s in MidwifeSchedule.objects.all().iterator():
        Resp.objects.get_or_create(
            schedule=s,
            defaults={"response_status": "scheduled"},
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("areas", "0012_repair_schedule_response_columns_retry"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="midwifeschedule",
                    name="cancellation_reason",
                ),
                migrations.RemoveField(
                    model_name="midwifeschedule",
                    name="cancelled_at",
                ),
                migrations.RemoveField(
                    model_name="midwifeschedule",
                    name="cancelled_by",
                ),
                migrations.RemoveField(
                    model_name="midwifeschedule",
                    name="confirmed_at",
                ),
                migrations.RemoveField(
                    model_name="midwifeschedule",
                    name="response_status",
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name="MidwifeScheduleResponse",
            fields=[
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="response_detail",
                        serialize=False,
                        to="areas.midwifeschedule",
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "midwife_schedule_responses",
                "ordering": ["schedule"],
            },
        ),
        migrations.RunPython(backfill_response_rows, migrations.RunPython.noop),
    ]
